### ISSUE TITLE
Ubuntu 16.04.3 LTS building error

### ISSUE THREAD

**Issue by denyspozniak** [ossobv/bcg729-deb#1]
Hello!

Could you check why I could not build package in Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-105-generic x86_64) ?

[bcg729_console_log.txt](https://github.com/ossobv/bcg729-deb/files/1819258/bcg729_console_log.txt)

**Comment by wdoekes** [comment]
```
 32550K .......... .......... .......... .......... .......... 99%  634K 0s
 32600K .......... .......... .......... .......... .......... 99% 74.9M 0s
 32650K ....                                                  100% 8604G=3.0s

2018-03-16 20:39:26 (10.7 MB/s) - \91bcg729-patterns.zip\92 saved [33438219/33438219]

Error: bad checksum on bcg729-patterns.zip downloaded from http://www.belledonne-communications.com/downloads/.\nTry again
FAIL testCampaignAll-exec (exit status: 1)
```
Is a test case failure, and an odd one at that. Looks like the downloaded zip is corrupt? Not really something to do with the packaging.

You could:
- try again
- report the error upstream (at the bcg maintainers, who create and maintain the tests)
- ignore the tests using `DEB_BUILD_OPTIONS=nocheck`

**Comment by denyspozniak** [comment]
_ignore the tests using DEB_BUILD_OPTIONS=nocheck_ - Works! Thanks!

**Comment by andrewvmail** [comment]
👍 on ```DEB_BUILD_OPTIONS=nocheck``` i had to also add a -b switch  for Debian 9

**Comment by wdoekes** [comment]
I suppose #2 fixes this :)
