### ISSUE TITLE
build fails with  bcg729 master

### ISSUE THREAD

**Issue by juha-h** [ossobv/bcg729-deb#5]
Debian build works OK with bcg729 tag 1.0.4., which is three years old.  So I tried with latest master and got configure error:
```
configure: exit 1
dh_auto_configure: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-static --enable-shared returned exit code 1
make[1]: *** [debian/rules:27: override_dh_auto_configure] Error 255
```
Please close if there is no intention to keep bcg729-deb up to date with bcg729 master.

**Comment by wdoekes** [comment]
So.....

There are no code changes other than some build config changes between 1.0.4 and 1.0.4-28-g9d24e2d. (And the following version change, which I'm not sure is effective yet.)
```
-cmake_minimum_required(VERSION 3.0)
-project(bcg729 VERSION 1.0.4 LANGUAGES C)
+cmake_minimum_required(VERSION 3.1)
+project(bcg729 VERSION 1.1.0 LANGUAGES C)
```
I'm not sure why you'd want that version.

If there are actual changes, it might be worth to spend time/effort on this.

**Comment by henningw** [comment]
Some days ago they released version 1.1.0 as tag, which includes some of the fixes you added as dedicated patches. There might be other extensions, but did not checked in detail yet.

**Comment by juha-h** [comment]
Henning Westerholt writes:

> Some days ago they released version 1.1.0 as tag, which includes some
> of the fixes you added as dedicated patches. There might be other
> extensions, but did not checked in detail yet.

In which repo they was 1.1.0 tag released?
This one https://github.com/ossobv/bcg729-deb only has v1.0.4-0osso3.

**Comment by henningw** [comment]
The upstream one: https://github.com/BelledonneCommunications/bcg729

**Comment by juha-h** [comment]
Henning Westerholt writes:

> The upstream one: https://github.com/BelledonneCommunications/bcg729

Yes, tried with that and the bebian build fails the same way as before.

**Comment by juha-h** [comment]
The build process does not use autotools anymore:
```
Building by Autotools way is deprecated. Use [CMake][cmake-website] to configure the source code.

	cmake . -DCMAKE_INSTALL_PREFIX=<prefix> -DCMAKE_PREFIX_PATH=<search_prefixes>
```
So looks like debian/rules needs to be rewritten.

**Comment by henningw** [comment]
Yes, i gave it a quick try, was not working as well.

**Comment by juha-h** [comment]
It works with this kind very simple debian/rules:
```
#!/usr/bin/make -f

# Uncomment this to turn on verbose mode.
# export DH_VERBOSE=1

# Uncomment this to change the hardening options
export DEB_BUILD_MAINT_OPTIONS = hardening=+all

DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)

%:
	dh $@
```

**Comment by juha-h** [comment]
Try with this:

[https://github.com/juha-h/bcg729-deb](url)

**Comment by wdoekes** [comment]
Probably not an issue anymore...
