### ISSUE TITLE
dockerfile fails many ways

### ISSUE THREAD

**Issue by james-see** [ossobv/bcg729-deb#8]
`executor failed running [/bin/sh -c mk-build-deps --install --remove --tool "apt-get -y" /build/debian/control]: exit code: 1`

**Comment by wdoekes** [comment]
Do you have any more output? Which OS are you using to build on? What commands do you use to build?

**Comment by james-see** [comment]
@wdoekes I used the readme.

**Comment by james-see** [comment]
It literally says in the Readme, "Just do ./Dockerfile.build". The error posted above is the result of running that command.

**Comment by wdoekes** [comment]
Why are you using this if you're not altering the `Dockerfile.build` parameters?

```
$ docker run debian:bullseye sh -c 'apt-get update -qq && apt-cache search bcg729'
libbcg729-0 - ITU G.729 Annex A compatible audio codec
libbcg729-dev - Development files for the ITU G.729 compatible audio codec
```

As you can see, the packages are already in vanilla bullseye.
